import { randomBytes } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

export const CONFIG_DIRECTORY = ".marketlens";
export const CONFIG_FILE = "config.json";
export const ENVIRONMENT_FILE = ".env";

export const defaultConfig = Object.freeze({
  version: 1,
  database: { mode: "embedded" },
  provider: "openstreetmap",
  ai: { enabled: false, provider: null },
  web: { port: 3000, host: "localhost" },
});

export function getLocalPaths(rootDirectory) {
  const localDirectory = join(rootDirectory, CONFIG_DIRECTORY);

  return {
    config: join(localDirectory, CONFIG_FILE),
    environment: join(rootDirectory, ENVIRONMENT_FILE),
    localDirectory,
    logs: join(localDirectory, "logs"),
    data: join(localDirectory, "data"),
  };
}

export async function readConfig(rootDirectory) {
  const { config } = getLocalPaths(rootDirectory);

  try {
    const value = JSON.parse(await readFile(config, "utf8"));
    return validateConfig(value);
  } catch (error) {
    if (error && typeof error === "object" && error.code === "ENOENT") {
      return null;
    }

    throw new Error(
      `Unable to read ${CONFIG_DIRECTORY}/${CONFIG_FILE}: ${formatError(error)}`,
    );
  }
}

export async function writeConfig(rootDirectory, config) {
  const paths = getLocalPaths(rootDirectory);
  const validated = validateConfig(config);

  await mkdir(paths.localDirectory, { recursive: true });
  await mkdir(paths.logs, { recursive: true });
  await mkdir(paths.data, { recursive: true });
  await writeFile(
    paths.config,
    `${JSON.stringify(validated, null, 2)}\n`,
    "utf8",
  );

  return paths;
}

export async function writeEnvironment(rootDirectory, config, options = {}) {
  const { overwrite = false } = options;
  const paths = getLocalPaths(rootDirectory);
  let existingEnvironment = null;

  try {
    existingEnvironment = await readFile(paths.environment, "utf8");
    if (!overwrite) {
      return { created: false, path: paths.environment };
    }
  } catch (error) {
    if (!(error && typeof error === "object" && error.code === "ENOENT")) {
      throw error;
    }
  }

  const content = createEnvironment(config, {
    databasePassword:
      readEnvironmentValue(existingEnvironment, "POSTGRES_PASSWORD") ??
      createDatabasePassword(),
    databaseUrl: readEnvironmentValue(existingEnvironment, "DATABASE_URL"),
    geminiApiKey: readEnvironmentValue(existingEnvironment, "GEMINI_API_KEY"),
    googleMapsApiKey: readEnvironmentValue(
      existingEnvironment,
      "GOOGLE_MAPS_API_KEY",
    ),
    overpassApiUrl: readEnvironmentValue(
      existingEnvironment,
      "OVERPASS_API_URL",
    ),
    overpassTimeoutSeconds: readEnvironmentValue(
      existingEnvironment,
      "OVERPASS_TIMEOUT_SECONDS",
    ),
  });
  await mkdir(dirname(paths.environment), { recursive: true });
  await writeFile(paths.environment, content, "utf8");

  return { created: true, path: paths.environment };
}

export function createEnvironment(config, options = {}) {
  const validated = validateConfig(config);
  const databasePassword = options.databasePassword ?? createDatabasePassword();
  const values = [
    "# Generated by MarketLens CLI. Keep this file local.",
    `PORT=${validated.web.port}`,
    "ENABLE_AUTH=false",
    `ENABLE_AI=${validated.ai.enabled}`,
    `DEFAULT_PLACE_PROVIDER=${validated.provider}`,
    `OVERPASS_API_URL=${options.overpassApiUrl ?? "https://overpass-api.de/api/interpreter"}`,
    `OVERPASS_TIMEOUT_SECONDS=${options.overpassTimeoutSeconds ?? "25"}`,
    `GOOGLE_MAPS_API_KEY=${options.googleMapsApiKey ?? ""}`,
    `GEMINI_API_KEY=${options.geminiApiKey ?? ""}`,
    "POSTGRES_DB=marketlens",
    "POSTGRES_USER=marketlens",
    `POSTGRES_PASSWORD=${databasePassword}`,
    "# Google Maps Scraper proxy configuration (optional)",
    `SCRAPER_PROXY_URL=${options.scraperProxyUrl ?? ""}`,
    `SCRAPER_PROXY_LIST=${options.scraperProxyList ?? ""}`,
    `SCRAPER_PROXY_ROTATION=${options.scraperProxyRotation ?? "false"}`,
  ];

  if (validated.database.mode === "external") {
    values.push(
      `DATABASE_URL=${options.databaseUrl ?? "postgresql://USER:PASSWORD@HOST:5432/marketlens?schema=public"}`,
    );
  } else if (validated.database.mode === "embedded") {
    values.push(
      "DATABASE_URL=postgresql://marketlens:local@127.0.0.1:5432/marketlens?schema=public",
      "MARKETLENS_RUNTIME=embedded",
    );
  }

  return `${values.join("\n")}\n`;
}

export function readEnvironmentValue(content, name) {
  if (!content) return null;

  const matches = [...content.matchAll(new RegExp(`^${name}=(.+)$`, "gm"))];
  return matches.at(-1)?.[1]?.trim() || null;
}

function createDatabasePassword() {
  return randomBytes(24).toString("base64url");
}

export function validateConfig(config) {
  if (!config || typeof config !== "object") {
    throw new Error("Configuration must be an object.");
  }

  const databaseMode = config.database?.mode;
  const provider = config.provider;
  const port = config.web?.port;
  const host = config.web?.host;
  const aiEnabled = config.ai?.enabled;
  const aiProvider = config.ai?.provider;

  if (!["embedded", "docker", "external"].includes(databaseMode)) {
    throw new Error(
      "Database mode must be 'embedded', 'docker', or 'external'.",
    );
  }
  if (
    !["openstreetmap", "google-places", "google-maps-scraper"].includes(
      provider,
    )
  ) {
    throw new Error(
      "Provider must be 'openstreetmap', 'google-places', or 'google-maps-scraper'.",
    );
  }
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error("Web port must be an integer between 1 and 65535.");
  }
  if (host !== "localhost" && host !== "127.0.0.1") {
    throw new Error("Local CLI installations may bind only to localhost.");
  }
  if (typeof aiEnabled !== "boolean") {
    throw new Error("AI enabled must be a boolean.");
  }
  if (
    aiEnabled &&
    !["gemini", "ollama", "openai-compatible"].includes(aiProvider)
  ) {
    throw new Error(
      "An enabled AI configuration must choose a supported provider.",
    );
  }

  return {
    version: 1,
    database: { mode: databaseMode },
    provider,
    ai: { enabled: aiEnabled, provider: aiEnabled ? aiProvider : null },
    web: { port, host },
  };
}

function formatError(error) {
  return error instanceof Error ? error.message : String(error);
}
