import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { configFromArguments, main } from "./index.js";
import {
  assertExternalDatabaseConfigured,
  composeArguments,
  createMarketLensCli,
} from "./marketlens-cli.js";

test("init writes a local configuration without credentials", async (t) => {
  const installationDirectory = await mkdtemp(
    join(tmpdir(), "marketlens-cli-"),
  );
  const sourceDirectory = await mkdtemp(join(tmpdir(), "marketlens-source-"));
  t.after(async () => {
    await rm(installationDirectory, { force: true, recursive: true });
    await rm(sourceDirectory, { force: true, recursive: true });
  });
  await writeFile(
    join(sourceDirectory, "docker-compose.yml"),
    "services: {}\n",
  );

  const cli = createMarketLensCli({
    cwd: installationDirectory,
    sourceDirectory,
  });
  const result = await cli.init(configFromArguments(["--port", "3010"]));
  const configuration = JSON.parse(
    await readFile(
      join(installationDirectory, ".marketlens", "config.json"),
      "utf8",
    ),
  );
  const environment = await readFile(
    join(installationDirectory, ".env"),
    "utf8",
  );

  assert.equal(result.runtimeDirectory, sourceDirectory);
  assert.equal(configuration.web.port, 3010);
  assert.match(
    environment,
    /^# Generated by MarketLens CLI\. Keep this file local\./,
  );
  assert.match(environment, /^POSTGRES_PASSWORD=[\w-]{32}$/m);
});

test("external database mode uses an explicit runtime override", async (t) => {
  const installationDirectory = await mkdtemp(
    join(tmpdir(), "marketlens-cli-"),
  );
  t.after(() => rm(installationDirectory, { force: true, recursive: true }));
  await writeFile(
    join(installationDirectory, ".env"),
    "DATABASE_URL=postgresql://user:password@database.example:5432/marketlens\n",
  );

  await assertExternalDatabaseConfigured(installationDirectory);
  assert.deepEqual(
    composeArguments(installationDirectory, "/runtime", {
      database: { mode: "external" },
    }),
    [
      "compose",
      "--project-directory",
      "/runtime",
      "--env-file",
      join(installationDirectory, ".env"),
      "-f",
      join("/runtime", "docker-compose.yml"),
      "-f",
      join("/runtime", "docker-compose.external.yml"),
    ],
  );
});

test("command parsing and help remain non-interactive", async () => {
  const config = configFromArguments([
    "--provider",
    "google-places",
    "--ai",
    "ollama",
    "--port",
    "4100",
  ]);
  const messages = [];

  const exitCode = await main(["help"], {
    stdout: (message) => messages.push(message),
  });

  assert.deepEqual(config.ai, { enabled: true, provider: "ollama" });
  assert.equal(config.provider, "google-places");
  assert.equal(config.web.port, 4100);
  assert.equal(exitCode, 0);
  assert.match(messages[0], /marketlens init/);
});
